name: FTP Deploy

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que estás usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SERVER }}        # Aquí va el servidor FTP
        username: ${{ secrets.USERNAME }}    # Usuario FTP
        password: ${{ secrets.PASSWORD }}    # Contraseña FTP
        protocol: ftp                        # Método de transferencia, puede ser "ftp", "ftps", o "sftp"
        local-dir: ./                        # Directorio local a subir, puedes especificar otro si lo prefieres
        server-dir: /public_html/             # Directorio remoto en tu servidor cPanel




