name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Cambia esto si deseas usar otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to cPanel
        run: |
          ssh -o StrictHostKeyChecking=no concejofsa@concejoformosa.org "cd /home/concejofsa/public_html && git pull origin main"


