name: FTP Deploy

on:
  push:
    branches:
      - main  # Cambia "main" por la rama que estás usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SERVER }}          # ftp.concejoformosa.org
        username: ${{ secrets.USERNAME }}      # concejofsaftp@concejoformosa.org
        password: ${{ secrets.PASSWORD }}      # Contraseña del FTP
        protocol: ftps                         # Cambiado a "ftps" para usar FTPS explícito
        port: 21                               # Puerto 21 para FTP/FTPS
        local-dir: ./dist/                          # Directorio local a subir
        server-dir: /public_html/              # Directorio remoto, asegúrate de que termine con '/'
         # Directorio remoto en tu servidor cPanel




