name: FTP Deploy

on:
  push:
    branches:
      - main  # Cambia "main" por la rama de tu proyecto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{ secrets.SERVER }}
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.PASSWORD }}
        local-dir: ./ # El directorio local a subir, puedes especificar otro si lo prefieres
        server-dir: /public_html # Directorio remoto en tu servidor cPanel
        method: ftp



